import {Noto_Sans_Devanagari} from "next/font/google";
import "./globals.css";
import Container from "@/components/Container";
import Header from "@/components/Header";
import TopStrip from "@/components/TopStrip";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";
import { TranslationProvider } from '@/contexts/TranslationContext';

const Noto_Sans_DevanagariSans = Noto_Sans_Devanagari({
  variable: "--font-Noto_Sans_Devanagari-sans",
  subsets: ["devanagari"],
});

export const metadata = {
  title: "Yuva Janta Sanghars Samiti",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="hi">


      <body suppressHydrationWarning
        className={`${Noto_Sans_DevanagariSans.className} antialiased`}
      >
        <TranslationProvider>
          <TopStrip/>
          <Header/>
          {children}
          <Footer/>        
          <Toaster position="top-center"  richColors/>
        </TranslationProvider>
      </body>
    </html>
  );
}
