import {Noto_Sans_Devanagari} from "next/font/google";
import "./globals.css";
import Container from "@/components/Container";
import Header from "@/components/Header";
import TopStrip from "@/components/TopStrip";
import Footer from "@/components/Footer";


const Noto_Sans_DevanagariSans = Noto_Sans_Devanagari({
  variable: "--font-Noto_Sans_Devanagari-sans",
  subsets: ["devanagari"],
});



export const metadata = {
  title: "Yuva Janta Sanghars Samiti",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning
        className={`${Noto_Sans_DevanagariSans.className} antialiased`}
      >
        <TopStrip/>
        <Header/>
        {children}
        <Footer/>        
      </body>
    </html>
  );
}
